//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarcodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class stringRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal stringRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BarcodeGenerator.Properties.stringRes", typeof(stringRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 barcodeTemplate.csv 的本地化字符串。
        /// </summary>
        internal static string barcodeTemplate {
            get {
                return ResourceManager.GetString("barcodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 barcodeTemplateOrg.csv 的本地化字符串。
        /// </summary>
        internal static string barcodeTemplateOrg {
            get {
                return ResourceManager.GetString("barcodeTemplateOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先切换到项目名视图！ 的本地化字符串。
        /// </summary>
        internal static string change2PanelViewModelPlease {
            get {
                return ResourceManager.GetString("change2PanelViewModelPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Config\ 的本地化字符串。
        /// </summary>
        internal static string configFolder {
            get {
                return ResourceManager.GetString("configFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 constrain.cfg 的本地化字符串。
        /// </summary>
        internal static string constrainTestsConfigFile {
            get {
                return ResourceManager.GetString("constrainTestsConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Data\ 的本地化字符串。
        /// </summary>
        internal static string dataFolder {
            get {
                return ResourceManager.GetString("dataFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \t 的本地化字符串。
        /// </summary>
        internal static string delimiterBarcodeTemplate {
            get {
                return ResourceManager.GetString("delimiterBarcodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dilution 的本地化字符串。
        /// </summary>
        internal static string dilution {
            get {
                return ResourceManager.GetString("dilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dilution1Step.cfg 的本地化字符串。
        /// </summary>
        internal static string Dilution1StepCfg {
            get {
                return ResourceManager.GetString("Dilution1StepCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dilution2Step.cfg 的本地化字符串。
        /// </summary>
        internal static string Dilution2StepCfg {
            get {
                return ResourceManager.GetString("Dilution2StepCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dilution.cfg 的本地化字符串。
        /// </summary>
        internal static string dilutionDefFile {
            get {
                return ResourceManager.GetString("dilutionDefFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \DilutionJoblists\ 的本地化字符串。
        /// </summary>
        internal static string dilutionJoblists {
            get {
                return ResourceManager.GetString("dilutionJoblists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DilutionLimsID 的本地化字符串。
        /// </summary>
        internal static string DilutionLimsID {
            get {
                return ResourceManager.GetString("DilutionLimsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoPredilution 的本地化字符串。
        /// </summary>
        internal static string doPredilution {
            get {
                return ResourceManager.GetString("doPredilution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \DummyTests\ 的本地化字符串。
        /// </summary>
        internal static string dummyFolder {
            get {
                return ResourceManager.GetString("dummyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C:\ProgramData\Tecan\EVOware\database\\processes\\ 的本地化字符串。
        /// </summary>
        internal static string EvoProcessFolder {
            get {
                return ResourceManager.GetString("EvoProcessFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Groups\ 的本地化字符串。
        /// </summary>
        internal static string groupFolder {
            get {
                return ResourceManager.GetString("groupFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \GroupSumUp\ 的本地化字符串。
        /// </summary>
        internal static string groupSumFolder {
            get {
                return ResourceManager.GetString("groupSumFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \joblists\ 的本地化字符串。
        /// </summary>
        internal static string joblists {
            get {
                return ResourceManager.GetString("joblists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 layout.cfg 的本地化字符串。
        /// </summary>
        internal static string layoutConfigFile {
            get {
                return ResourceManager.GetString("layoutConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 m 的本地化字符串。
        /// </summary>
        internal static string mannualMode {
            get {
                return ResourceManager.GetString("mannualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BarcodeGenerator 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string nullPanel {
            get {
                return ResourceManager.GetString("nullPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Output\ 的本地化字符串。
        /// </summary>
        internal static string outputFolder {
            get {
                return ResourceManager.GetString("outputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 p 的本地化字符串。
        /// </summary>
        internal static string posIDMode {
            get {
                return ResourceManager.GetString("posIDMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Predilute 的本地化字符串。
        /// </summary>
        internal static string Predilute {
            get {
                return ResourceManager.GetString("Predilute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \ResultIsOk.txt 的本地化字符串。
        /// </summary>
        internal static string resFile {
            get {
                return ResourceManager.GetString("resFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sampleCountPerPlate 的本地化字符串。
        /// </summary>
        internal static string sampleCountPerPlate {
            get {
                return ResourceManager.GetString("sampleCountPerPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sampleGrids 的本地化字符串。
        /// </summary>
        internal static string sampleGrids {
            get {
                return ResourceManager.GetString("sampleGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sampleGrids 的本地化字符串。
        /// </summary>
        internal static string sampleGrids1 {
            get {
                return ResourceManager.GetString("sampleGrids1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 s 的本地化字符串。
        /// </summary>
        internal static string scanGunMode {
            get {
                return ResourceManager.GetString("scanGunMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selection\ 的本地化字符串。
        /// </summary>
        internal static string selectionFolder {
            get {
                return ResourceManager.GetString("selectionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 shelfColumns 的本地化字符串。
        /// </summary>
        internal static string shelfColumns {
            get {
                return ResourceManager.GetString("shelfColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Tests2Do\ 的本地化字符串。
        /// </summary>
        internal static string testFolder {
            get {
                return ResourceManager.GetString("testFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unknown 的本地化字符串。
        /// </summary>
        internal static string unknownBarcode {
            get {
                return ResourceManager.GetString("unknownBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 杂项 的本地化字符串。
        /// </summary>
        internal static string userSelPanel {
            get {
                return ResourceManager.GetString("userSelPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.03 的本地化字符串。
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Working\ 的本地化字符串。
        /// </summary>
        internal static string workingFolder {
            get {
                return ResourceManager.GetString("workingFolder", resourceCulture);
            }
        }
    }
}
